# -*- coding: utf-8 -*-
"""decisiontree5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1faAocmfGAnsLNFt_5Sx0Hp1yywqj6aRy
"""

import yfinance as yf
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier

# =========================
# CONFIG
# =========================
TICKER = "BA"
START_DATE = "2016-01-01"
MAX_DEPTH = 5
MIN_SAMPLES_LEAF = 40

# =========================
# LOAD DATA
# =========================
df = yf.download(
    TICKER,
    start=START_DATE,
    auto_adjust=True,
    progress=False
)

# Fix MultiIndex columns
if isinstance(df.columns, pd.MultiIndex):
    df.columns = df.columns.get_level_values(0)

df = df.reset_index()

# =========================
# INDICATORS
# =========================

# --- Returns
df["return_1d"] = df["Close"].pct_change(1)
df["return_5d"] = df["Close"].pct_change(5)

# --- Volatility (10-day rolling)
df["volatility_10"] = df["return_1d"].rolling(10).std()

# --- RSI (14, SMA-based)
delta = df["Close"].diff()
gain = delta.clip(lower=0)
loss = -delta.clip(upper=0)
rs = gain.rolling(14).mean() / loss.rolling(14).mean()
df["rsi"] = 100 - (100 / (1 + rs))

# --- Relative Volume (20)
df["rel_volume"] = df["Volume"] / df["Volume"].rolling(20).mean()

# --- MACD Histogram (macd_diff)
ema12 = df["Close"].ewm(span=12, adjust=False).mean()
ema26 = df["Close"].ewm(span=26, adjust=False).mean()
macd = ema12 - ema26
signal = macd.ewm(span=9, adjust=False).mean()
df["macd_diff"] = macd - signal

# =========================
# TARGET (BUY NEXT DAY)
# =========================
df["forward_return"] = df["Close"].shift(-1) / df["Open"].shift(-1) - 1
df["target"] = (df["forward_return"] > 0).astype(int)

# =========================
# MODEL DATA
# =========================
features = [
    "rsi",
    "rel_volume",
    "macd_diff",
    "return_1d",
    "return_5d",
    "volatility_10"
]

df = df.dropna()
X = df[features]
y = df["target"]

# =========================
# TRAIN DECISION TREE
# =========================
model = DecisionTreeClassifier(
    max_depth=MAX_DEPTH,
    min_samples_leaf=MIN_SAMPLES_LEAF,
    random_state=42
)

model.fit(X, y)

# =========================
# LEAF ANALYSIS
# =========================
df["leaf"] = model.apply(X)

results = []

for leaf in df["leaf"].unique():
    subset = df[df["leaf"] == leaf]

    if len(subset) < MIN_SAMPLES_LEAF:
        continue

    results.append({
        "leaf": leaf,
        "win_rate": subset["target"].mean(),
        "avg_gain": subset["forward_return"].mean(),
        "samples": len(subset)
    })

best = max(results, key=lambda x: x["avg_gain"])
best_leaf_id = best["leaf"]

# =========================
# EXTRACT RULES
# =========================
tree = model.tree_

def extract_rules(node=0, path=None):
    if path is None:
        path = []

    if tree.children_left[node] == -1:
        return [(node, path)]

    feature = features[tree.feature[node]]
    threshold = tree.threshold[node]

    left = extract_rules(
        tree.children_left[node],
        path + [f"{feature} <= {threshold:.6f}"]
    )
    right = extract_rules(
        tree.children_right[node],
        path + [f"{feature} > {threshold:.6f}"]
    )

    return left + right

rules = extract_rules()
best_rules = next(r for r in rules if r[0] == best_leaf_id)

# =========================
# PRINT BEST RULE SET
# =========================
print("\n=== BEST INDICATOR COMBINATION ===")
for rule in best_rules[1]:
    print(rule)

print(f"\nAvg Gain: {best['avg_gain']*100:.2f}%")
print(f"Win Rate: {best['win_rate']*100:.2f}%")
print(f"Samples: {best['samples']}")

# =========================
# PRINT ALL SIGNAL DAYS
# =========================
signal_days = df[df["leaf"] == best_leaf_id].copy()
signal_days["buy_date"] = signal_days["Date"].shift(-1)

print("\n=== ALL BUY SIGNALS (CRITERIA MET ON DAY N) ===\n")

for _, row in signal_days.iterrows():
    print(
        f"Signal Date: {row['Date'].date()} | "
        f"Buy Date: {row['buy_date'].date()} | "
        f"RSI: {row['rsi']:.2f} | "
        f"RelVol: {row['rel_volume']:.2f} | "
        f"MACD_diff: {row['macd_diff']:.5f} | "
        f"Ret1D: {row['return_1d']*100:.2f}% | "
        f"Ret5D: {row['return_5d']*100:.2f}% | "
        f"Volatility: {row['volatility_10']:.4f} | "
        f"Next-Day Return: {row['forward_return']*100:.2f}%"
    )